// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGmikkGX-yIHZ_ZLFh36Flm-jAhdelU8',
    appId: '1:546456672408:web:384d180d9a4499daea18ed',
    messagingSenderId: '546456672408',
    projectId: 'mlsc-bot',
    authDomain: 'mlsc-bot.firebaseapp.com',
    databaseURL: 'https://mlsc-bot-default-rtdb.firebaseio.com',
    storageBucket: 'mlsc-bot.appspot.com',
    measurementId: 'G-SWRDB6FJKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7gBNq7pR3TQc_cpoBKE-IYl5OOcmm-w8',
    appId: '1:546456672408:android:a436510c4b70eb1eea18ed',
    messagingSenderId: '546456672408',
    projectId: 'mlsc-bot',
    databaseURL: 'https://mlsc-bot-default-rtdb.firebaseio.com',
    storageBucket: 'mlsc-bot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAooiBxtwbJ1JD0Vxk48N4CZL3XNn8E2bA',
    appId: '1:546456672408:ios:11c45b03f7bf50acea18ed',
    messagingSenderId: '546456672408',
    projectId: 'mlsc-bot',
    databaseURL: 'https://mlsc-bot-default-rtdb.firebaseio.com',
    storageBucket: 'mlsc-bot.appspot.com',
    iosClientId: '546456672408-djbiu3pkhpe423qf2e7h6sqpoiorokoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitHub',
  );
}
